<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<StartupObject>Sub Main</StartupObject>
		<UseWindowsForms>true</UseWindowsForms>
		<MyType>WindowsForms</MyType>
		<ApplicationIcon>favicon(2).ico</ApplicationIcon>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<Version>1.1.1.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="favicon(2).ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Import Include="System.Data" />
		<Import Include="System.Drawing" />
		<Import Include="System.Windows.Forms" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
		<PackageReference Include="LiveChartsCore" Version="2.0.0-rc5.4" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView" Version="2.0.0-rc5.4" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView.WinForms" Version="2.0.0-rc5.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="QuestPDF" Version="2025.12.3" />
		<PackageReference Include="SkiaSharp" Version="3.119.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="My Project\Application.Designer.vb">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Application.myapp</DependentUpon>
		</Compile>
		<Compile Update="My Project\Resources.Designer.vb">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="My Project\Application.myapp">
			<Generator>MyApplicationCodeGenerator</Generator>
			<LastGenOutput>Application.Designer.vb</LastGenOutput>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Data\" />
		<Folder Include="Models\" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="MessagingToolkit.Barcode">
			<HintPath>Lib\MessagingToolkit.Barcode.dll</HintPath>
			<CopyLocal>True</CopyLocal>
		</Reference>
		<Reference Include="MessagingToolkit.QRCode">
			<HintPath>Lib\MessagingToolkit.QRCode.dll</HintPath>
			<CopyLocal>True</CopyLocal>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="My Project\Resources.resx">
			<CustomToolNamespace>My.Resources</CustomToolNamespace>
			<Generator>VbMyResourcesResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.vb</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>